#pragma once

#include "../../Types.h"

enum class eServer : PacketType
{
	None = 0,
	Test,
	LoginFailure_AlreadyLoggedIn,
	LoginFailure_Full,
	LoginSuccess,
	LobbyChat,
	LobbyUpdateInfo_UserList,
	LobbyUpdateInfo_RoomList,
	CreateRoom_Success,
	CreateRoom_Fail,
	EnterRoom_Success,
	EnterRoom_Full,
	EnterRoom_InGame,
	EnterRoom_NoRoom,
	ExitRoom,
	StartGame_Success,
	StartGame_Fail,
	NotifyRoomUserEnter,
	NotifyRoomUserExit,
	RoomChat,
	RoomUsersInfo,
	RoomReady,
	RoomReady_Fail,
	RoomStandby,
	RoomStandby_Fail,
	RoomMapChoice,
	RoomCharacterChoice,
	InGameExit,
	GameOver,
	CheckedClientInfo,
	ConnectionID,

	C_BeginMove,
	C_Moving,
	C_EndMove,
	C_MonsterAttack,
	C_BeginMoveMonster,
	C_Attack,
	C_AttackReq,
	C_RangedAttack,
	C_RangedAttackReq,
	C_AllCreaturesInfo,
	C_Ready,
	C_Start,
	C_NextStage,
	C_MapClear,
	C_StageClear,
	C_Annihilated,
	C_PlayerHit,
	Max,
};

enum class eClient : PacketType
{
	None = 0,
	Test,
	LoginReq,
	LobbyChat,
	LobbyUpdateInfo,
	UserListGetPageInfo,
	RoomListGetPageInfo,
	CreateRoom,
	EnterRoom,
	ExitRoom,
	StartGame,
	RoomReady,
	RoomStandby,
	RoomChat,
	ReqRoomUsersInfo,
	RoomMapChoice,
	RoomCharacterChoice,
	BeginMove,
	EndMove,
	MonsterAttack,
	BeginMoveMonster,
	InGameExit,
	Attack,
	RangedAttack,
	GameOver,
	Max,
};